version: '3'
services:
  mysql:
    image: mysql
    environment:
      - "MYSQL_ROOT_PASSWORD=jc31d2qyy7h9jv5jn1u9uosjksxzaizw"
      - "MYSQL_USER=acp4pogynvaeidfj"
      - "MYSQL_PASSWORD=jc31d2qyy7h9jv5jn1u9uosjksxzaizw"
      - "MYSQL_DATABASE=dd"
    ports:
      - "3306:3306"
  maven:
    build:
      context: maven/
    volumes: 
      - type: volume
        source: data
        target: /home/war
  tomcat:
    build: 
      context: tomcat/
    volumes: 
      - type: volume
        source: data
        target: /opt/tomcat/webapps
    ports: 
      - "8080:8080"
    depends_on: 
      - maven
      - mysql
volumes: 
  data:
